import type { InventoryItem } from './inventory-bridge';

export const ETSY_STATES = ['PRODUCT_LOADED','IMAGE_UPLOAD','IMAGE_PROCESSING','IMAGE_REVIEW','KEYWORD_RESEARCH','IMAGE_ORDER','TITLE','CART_SUMMARY','VARIANT_PRICING','DESCRIPTION','ALT_TEXT','HOLIDAY','FINAL_REVIEW','COMPLETED'] as const;
export type EtsyState = (typeof ETSY_STATES)[number];
export const STEP_LABELS: Record<EtsyState,string> = { PRODUCT_LOADED:'Artikel', IMAGE_UPLOAD:'Bilder hinzufügen', IMAGE_PROCESSING:'Bilder bearbeiten', IMAGE_REVIEW:'Bilder freigeben', KEYWORD_RESEARCH:'Keywords', IMAGE_ORDER:'Bildreihenfolge', TITLE:'Titel', CART_SUMMARY:'Warenkorb', VARIANT_PRICING:'Preise', DESCRIPTION:'Beschreibung', ALT_TEXT:'Alt-Texte', HOLIDAY:'Feiertag', FINAL_REVIEW:'Final Check', COMPLETED:'Fertig' };
export const VISIBLE_STEPS: EtsyState[] = ['IMAGE_UPLOAD','IMAGE_REVIEW','KEYWORD_RESEARCH','IMAGE_ORDER','TITLE','CART_SUMMARY','VARIANT_PRICING','DESCRIPTION','ALT_TEXT','HOLIDAY','FINAL_REVIEW'];
export const DEPENDENCIES: Partial<Record<EtsyState,EtsyState[]>> = { IMAGE_REVIEW:['IMAGE_ORDER','ALT_TEXT'], KEYWORD_RESEARCH:['TITLE','DESCRIPTION'], IMAGE_ORDER:['ALT_TEXT'], VARIANT_PRICING:['DESCRIPTION'] };
export const HOLIDAYS = ['Weihnachten','Cinco de Mayo','Día de los Muertos','Diwali','Ostern','Eid','Vatertag','Halloween','Chanukka','Holi','Independence Day','Kwanzaa','Mondneujahr','Mardi Gras','Muttertag','Neujahr','Pessach','Ramadan','St. Patrick’s Day','Thanksgiving','Valentinstag','Veterans Day'];
export const DEFAULT_COPY = {
  shipping_de:'Kostenloser Versand ab 50 € im Inland mit dem Code „GRATISVERSAND“', shipping_en:'Free domestic shipping on orders over €50 with the code “GRATISVERSAND”.',
  color_de:'Deine Wunschfarbe ist nicht dabei? Schreib mir gern – weitere Farbtöne sind auf Anfrage möglich.', color_en:'Looking for another color? Send me a message – additional shades may be available on request.',
  manufacturing_de:'Jedes Exemplar wird einzeln 3D-gedruckt und sorgfältig nachbearbeitet. Feine sichtbare Drucklinien sind Teil dieser Fertigungsweise.', manufacturing_en:'Each piece is individually 3D printed and carefully finished. Fine visible print lines are part of this process.',
  sustainability_de:'Filamentreste und Fehldrucke werden gesammelt dem Recycling zugeführt. Geeignete gebrauchte Versandkartons werden wiederverwendet.', sustainability_en:'Filament scraps and failed prints are collected for recycling. Suitable used shipping boxes are reused.',
  safety_de:'Dekoratives Designobjekt, kein Spielzeug. Bei Bruch können scharfe Kanten entstehen. Nicht für Kinder unter 14 Jahren geeignet.', safety_en:'Decorative design object, not a toy. Broken parts may have sharp edges. Not suitable for children under 14.'
};
export function snapshotProduct(item: InventoryItem) { return { id:String(item.id), name:item.modelName, productType:item.productType, buyerWorld:item.buyerWorld, inventoryUpdatedAt:item.updatedAt, dimensions:{ width:item.widthMm,height:item.heightMm,depth:item.depthMm,unit:'mm' }, variants:item.variants.map(v=>({ id:String(v.id),name:v.name,size:v.size,weight:{value:v.weightGrams,unit:'g'} })) }; }
const tag=(v:string)=>v.trim().replace(/\s+/g,' ').slice(0,20);
export function generateKeywords(p:ReturnType<typeof snapshotProduct>) { const dark=/goth|halloween|dark|dämon|totenkopf/i.test(`${p.productType} ${p.buyerWorld}`); const pool=[p.productType,p.name,`${p.productType} Deko`,dark?'Gothic Deko':'Design Deko',dark?'Dark Academia Deko':'Skulptur Deko','Wohnaccessoire','Geschenk Deko','besondere Deko','Wohnzimmer Deko','Regal Dekoration','Sideboard Deko','kleine Skulptur','moderne Skulptur','Design Objekt','ruhige Dekoration','FormPoesie']; const tags=Array.from(new Set(pool.map(tag).filter(Boolean))).slice(0,13); while(tags.length<13) tags.push(`Deko Idee ${tags.length+1}`); return {primary_keyword:tag(`${p.productType} ${p.name}`),tags}; }
export function generateTitles(p:ReturnType<typeof snapshotProduct>,primary:string){ const candidates=[`${primary} | ${p.buyerWorld} | besondere Deko`,`${p.name} – ${p.productType} für Regal & Sideboard`,`${p.productType} ${p.name} | Designobjekt als Geschenkidee`].map((title,i)=>({id:String.fromCharCode(65+i),title:title.slice(0,140)})); return {candidates,recommended:'A',selected_title:candidates[0].title}; }
export const generateCartSummary=(p:ReturnType<typeof snapshotProduct>)=>({cart_summary:`${p.name}: ${p.productType} in ${p.variants.length} ${p.variants.length===1?'Variante':'Varianten'}.`});
export function generateDescription(p:ReturnType<typeof snapshotProduct>,primary:string,prices:Record<string,number|null>){ const size=(v:(typeof p.variants)[number])=>v.size||([p.dimensions.width,p.dimensions.depth,p.dimensions.height].every(x=>typeof x==='number')?`${p.dimensions.width} × ${p.dimensions.depth} × ${p.dimensions.height} mm`:''); const de=p.variants.map(v=>`• ${v.name}${size(v)?` – ${size(v)}`:''}${prices[v.id]?` – ${(prices[v.id]!/100).toLocaleString('de-DE',{style:'currency',currency:'EUR'})}`:''}`).join('\n'); const en=p.variants.map(v=>`• ${v.name}${size(v)?` – ${size(v)}`:''}${prices[v.id]?` – ${(prices[v.id]!/100).toLocaleString('en-GB',{style:'currency',currency:'EUR'})}`:''}`).join('\n'); return { description_de:`${p.name} ist eine ${p.productType}, die mit klarer Form und ruhiger Präsenz einen besonderen Akzent setzt. Die Suchidee „${primary}“ beschreibt das Objekt, ohne seinen Charakter auf ein Schlagwort zu reduzieren.\n\n📐 WÄHLE DEINE VARIANTE\n${de}\n\n✨ DESIGN & WIRKUNG\nAus verschiedenen Blickwinkeln entwickelt ${p.name} eine eigene Wirkung. Das Objekt kann allein stehen oder eine bewusst zusammengestellte Szenerie ergänzen.\n\n📦 VERSAND\n${DEFAULT_COPY.shipping_de}\n\n✨ FARBE & INDIVIDUALITÄT\n${DEFAULT_COPY.color_de}\n\n🛠️ HERSTELLUNG\n${DEFAULT_COPY.manufacturing_de}\n\n♻️ NACHHALTIGKEIT\n${DEFAULT_COPY.sustainability_de}\n\n⚠️ SICHERHEIT & PRODUKTHINWEISE\n${DEFAULT_COPY.safety_de}`, description_en:`${p.name} is a ${p.productType.toLowerCase()} with a clear shape and a calm presence. It creates a distinctive accent without overwhelming its surroundings.\n\n📐 CHOOSE YOUR VARIANT\n${en}\n\n✨ DESIGN & CHARACTER\nViewed from different angles, ${p.name} develops its own visual character. It can stand alone or become part of a thoughtfully composed scene.\n\n📦 SHIPPING\n${DEFAULT_COPY.shipping_en}\n\n✨ COLOR & INDIVIDUALITY\n${DEFAULT_COPY.color_en}\n\n🛠️ MAKING\n${DEFAULT_COPY.manufacturing_en}\n\n♻️ SUSTAINABILITY\n${DEFAULT_COPY.sustainability_en}\n\n⚠️ SAFETY & PRODUCT INFORMATION\n${DEFAULT_COPY.safety_en}` }; }
export function classifyHoliday(p:ReturnType<typeof snapshotProduct>){ const match=/halloween|goth|dämon|totenkopf|geist|hex/i.test(`${p.name} ${p.productType} ${p.buyerWorld}`); return match?{classification:'HOLIDAY_RELEVANT',recommended_holiday:'Halloween',reason:'Die Gestaltung passt zur Halloween-Suche, wirkt aber zugleich als ganzjährige Gothic-Dekoration.'}:{classification:'NO_HOLIDAY_RELATION',recommended_holiday:null,reason:'Das Produkt ist nicht erkennbar an einen einzelnen Feiertag gebunden.'}; }
export function imagePrompt(name:string,instruction=''){return `Edit only the background and staging around the photographed product “${name}”. Preserve the product exactly: shape, proportions, count, surface, logos, engravings, print details and perspective. Create a premium, calm, atmospheric FormPoesie product scene with a believable contact surface, natural shadow, consistent soft light and subtle props. The product remains the clear visual center. Props must not look included in the purchase.${instruction?` User request: ${instruction}`:''}`;}
